import ButtonContact from "@/components/ButtonContact/ButtonContact";
import Navbar from "@/components/Navbar/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"; // or `v14-appRouter` if you are using Next.js v14
import { Inter } from "next/font/google";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ICADVietnam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <main className="h-screen">
            {/* <div className="max-w-[1480px] w-full"> */}
            <Navbar />
            {/* </div> */}
            <div className="mt-[60px] lg:mt-0 w-full h-screen">{children}</div>
            {/* <Footer /> */}
            <ButtonContact />
          </main>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
